# Generated by Django 3.1.6 on 2021-02-15 22:45

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210215_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 22, 45, 45, 349586, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='root',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='network.post'),
        ),
    ]
