# Generated by Django 3.1.6 on 2021-02-17 22:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_auto_20210215_2245'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='following',
            field=models.ManyToManyField(related_name='_userprofile_following_+', to='network.UserProfile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 22, 38, 49, 855395, tzinfo=utc), verbose_name='Date Posted'),
        ),
    ]
