# Generated by Django 3.1.6 on 2021-02-18 00:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210217_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 0, 7, 4, 549524, tzinfo=utc), verbose_name='Date Followed'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 18, 0, 7, 4, 549043, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterUniqueTogether(
            name='followmodel',
            unique_together={('user', 'following')},
        ),
    ]
