# Generated by Django 3.1.6 on 2021-02-20 18:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0009_auto_20210220_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='followmodel',
            name='followed',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='network.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='followmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 18, 50, 19, 658836, tzinfo=utc), verbose_name='Date Followed'),
        ),
        migrations.AlterField(
            model_name='followmodel',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 18, 50, 19, 658368, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterUniqueTogether(
            name='followmodel',
            unique_together={('follower', 'followed')},
        ),
        migrations.RemoveField(
            model_name='followmodel',
            name='following',
        ),
    ]
