# Generated by Django 3.1.6 on 2021-02-20 20:05

import datetime
from django.db import migrations, models
import django.db.models.expressions
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_auto_20210220_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 20, 5, 38, 270976, tzinfo=utc), verbose_name='Date Followed'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 20, 20, 5, 38, 270489, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AddConstraint(
            model_name='followmodel',
            constraint=models.CheckConstraint(check=models.Q(_negated=True, follower=django.db.models.expressions.F('followed')), name='Follower matches following'),
        ),
    ]
