# Generated by Django 3.1.6 on 2021-02-21 03:41

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_auto_20210220_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 3, 41, 53, 984026, tzinfo=utc), verbose_name='Date Followed'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 3, 41, 53, 983533, tzinfo=utc), verbose_name='Date Posted'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
