# Generated by Django 3.1.6 on 2021-02-21 05:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_auto_20210221_0341'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='root_type',
            field=models.IntegerField(choices=[(0, 'Initial Post'), (1, 'Reply'), (2, 'Reshare')], default=0, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='followmodel',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 5, 55, 5, 647903, tzinfo=utc), verbose_name='Date Followed'),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_posted',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 21, 5, 55, 5, 647362, tzinfo=utc), verbose_name='Date Posted'),
        ),
    ]
